#This is a docker-compose default configuration, You can change as much as you need 
version: '3.7'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app-multer
    env_file:
      - ./.env
    ports:
      - 3002:3002
    volumes:
      - ./:/home/app
    networks:
      - venanjs-default      
    depends_on:
      - mysqldb
    links:
      - mysqldb

  mysqldb:
    image: mysql:8.0.21
    container_name: mysql-multer
    env_file:
      - ./.env
    ports:
      - 3308:3306
    volumes:
      - venanjs_default:/var/lib/mysql
    networks:
      - venanjs-default

networks:
  venanjs-default:
    driver: bridge

volumes:
  venanjs_default: {}